catnap/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from catnap import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^e/', include('equipment.urls', namespace="equipment")),
]

equipment/urls.py
from django.conf.urls import patterns, url 
from equipment import views

urlpatterns = [
    url(r'^equip/list/$', views.equip_list, name='equip_list'),
    url(r'^equip/addform/$', views.equip_addform, name='equip_addform'),
    url(r'^equip/add/$', views.equip_add, name='equip_add'),
    url(r'^equip/view/(?P<sid>\d+)/$', views.equip_view, name='equip_view'),
    url(r'^equip/updform/(?P<sid>\d+)/$', views.equip_updform, name='equip_updform'),
    url(r'^equip/upd/$', views.equip_upd, name='equip_upd'),
    url(r'^equip/history/view/(?P<sid>\d+)/$', views.equip_history_view, name='equip_history_view'),
    url(r'^equip/history/upd/(?P<sid>\d+)/$', views.equip_history_upd, name='equip_history_upd'),
    url(r'^equip/csv/$', views.equip_csv, name='equip_csv'),

    url(r'^code/list/$', views.code_list, name='code_list'),
    url(r'^code/addform/$', views.code_addform, name='code_addform'),
    url(r'^code/add/$', views.code_add, name='code_add'),
    url(r'^code/updform/(?P<sid>\d+)/$', views.code_updform, name='code_updform'),
    url(r'^code/upd/$', views.code_upd, name='code_upd'),

    url(r'^pjt/list/$', views.pjt_list, name='pjt_list'),
    url(r'^pjt/addform/$', views.pjt_addform, name='pjt_addform'),
    url(r'^pjt/add/$', views.pjt_add, name='pjt_add'),
    url(r'^pjt/updform/(?P<sid>\d+)/$', views.pjt_updform, name='pjt_updform'),
    url(r'^pjt/upd/$', views.project_upd, name='project_upd'),
]

equipment/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class CodeCategory(models.Model):
    category_name = models.CharField(max_length=100, unique=True)

    def __unicode__(self):  # __str__ on Python 3
        return str(self.id) + ' ' + self.category_name

    def serialize(self):
        data = {
            'id': self.id,
            'category_name': self.category_name,
        }
        return data


class Code(models.Model):
    code_category = models.ForeignKey(CodeCategory)
    code_name = models.CharField(max_length=100)

    def __unicode__(self):  # __str__ on Python 3
        return str(self.id) + ' ' + self.code_name

    def serialize(self):
        data = {
            'id': self.id,
            'category_id': self.code_category_id,
            'category_name': self.code_category.category_name,
            'code_name': self.code_name,
        }
        return data


class Equipment(models.Model):
    management_code = models.CharField(max_length=14, unique=True, help_text='yyyymmddhhmiss')
    equipment_code = models.ForeignKey(Code, related_name='equipment_code')
    model_no = models.CharField(max_length=200)
    serial_no = models.CharField(max_length=200, unique=True)
    purchase_ymd = models.CharField(max_length=10)
    purchase_price = models.IntegerField()
    discard_ymd = models.CharField(max_length=10)
    manufacturer_code = models.ForeignKey(Code, related_name='manufacturer_code')
    detail_info = models.TextField(blank=True)
    state_code = models.ForeignKey(Code, related_name='state_code')
    registered_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):  # __str__ on Python 3
        return self.model_no + ' : ' + self.serial_no


class Project(models.Model):
    project_name = models.CharField(max_length=200, unique=True)
    start_ymd = models.CharField(max_length=8)
    end_ymd = models.CharField(max_length=8)
    registered_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):  # __str__ on Python 3
        return self.project_name

    def serialize(self):
        data = {
            'id': self.id,
            'project_name': self.project_name,
            'start_ymd': self.start_ymd,
            'end_ymd': self.end_ymd,
        }
        return data


class History(models.Model):
    equipment = models.ForeignKey(Equipment)
    user_name = models.CharField(max_length=100)
    start_ymd = models.CharField(max_length=8)
    end_ymd = models.CharField(max_length=8)
    project = models.ForeignKey(Project)
    registered_date = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):  # __str__ on Python 3
        return self.user_name

    def serialize(self):
        data = {
            'id': self.id,
            'user_name': self.user_name,
            'start_ymd': self.start_ymd,
            'end_ymd': self.end_ymd,
            'registered_date': self.registered_date.__str__(),
            'equipment_name': self.equipment.__str__(),
            'project_name': self.project.project_name,
            'project_id': self.project_id,
        }
        return data

equipment/views.py
# -*- coding:utf-8 -*-

import unicodecsv as csv
import json
from datetime import datetime

from django.core.urlresolvers import reverse
from django.db.models.aggregates import Max
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.shortcuts import render
from django.template import RequestContext
# from django.views.decorators.csrf import csrf_exempt

# Create your views here.

from equipment.models import *


def equip_csv(request):
    equipment_code = request.GET.get('equipment_code')
    state_code = request.GET.get('state_code')
    project_code = request.GET.get('project_code')
    user_name = request.GET.get('user_name')

    kwargs = {}
    if equipment_code:
        kwargs.__setitem__('equipment_code__exact', equipment_code)
    if state_code:
        kwargs.__setitem__('state_code__exact', state_code)
    if project_code:
        kwargs.__setitem__('history__project_id__exact', project_code)
    if user_name:
        kwargs.__setitem__('history__user_name__contains', user_name)

    latest_equipment_list = Equipment.objects.all().filter(**kwargs).annotate(max_id=Max('history__end_ymd')).order_by(
        'registered_date')

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="somefilename.csv"'

    writer = csv.writer(response, encoding='utf-8')
    writer.writerow(['자산분류', '제조사', '모델번호', '시리얼번호', '취득가격', '취득일', '폐기(예정)일', '상태', '사용자', '사용종료(예정)일'])
    if latest_equipment_list:
        for equip in latest_equipment_list:
            last_user_name = ''
            last_user_ymd = ''

            for history in equip.history_set.iterator():
                if equip.max_id == history.end_ymd:
                    last_user_name = history.user_name
                    last_user_ymd = history.end_ymd
            writer.writerow([equip.equipment_code.code_name,
                             equip.manufacturer_code.code_name, equip.model_no,
                             equip.serial_no, equip.purchase_price, equip.purchase_ymd, equip.discard_ymd,
                             equip.state_code.code_name, last_user_name, last_user_ymd])
    return response


# @csrf_exempt
def equip_list(request, template='equipment/equip_list.html', page_template='equipment/equip_list_page.html'):
    equipment_code = request.GET.get('equipment_code')
    state_code = request.GET.get('state_code')
    project_code = request.GET.get('project_code')
    user_name = request.GET.get('user_name')
    type_list = Code.objects.filter(code_category_id=1).all()
    state_list = Code.objects.filter(code_category_id=3).all()
    project_list = Project.objects.all().order_by('start_ymd')

    kwargs = {}
    if equipment_code:
        kwargs.__setitem__('equipment_code__exact', equipment_code)
    if state_code:
        kwargs.__setitem__('state_code__exact', state_code)
    if project_code:
        kwargs.__setitem__('history__project_id__exact', project_code)
    if user_name:
        kwargs.__setitem__('history__user_name__contains', user_name)

    total_count = Equipment.objects.all().filter(**kwargs).count()
    latest_equipment_list = Equipment.objects.all().filter(**kwargs).annotate(max_id=Max('history__end_ymd')).order_by(
        'registered_date')

    if request.is_ajax():
        template = page_template

    context = {'latest_equipment_list': latest_equipment_list,
               'total_count': total_count,
               'type_list': type_list,
               'state_list': state_list,
               'project_list': project_list,
               'entries': latest_equipment_list,
               'page_template': page_template,
               'request': request,
               }

    return render_to_response(template, context, context_instance=RequestContext(request))


def equip_addform(request):
    type_list = Code.objects.filter(code_category_id=1).all()
    manufacturer_list = Code.objects.filter(code_category_id=2).all()
    state_list = Code.objects.filter(code_category_id=3).all()
    context = {'type_list': type_list, 'manufacturer_list': manufacturer_list, 'state_list': state_list}
    return render(request, 'equipment/equip_addform.html', context)


# @csrf_exempt
def equip_add(request):
    equip = Equipment()
    equip.management_code = datetime.today().strftime("%Y%m%d%H%M%S")
    equip.equipment_code = Code.objects.get(id=int(request.POST.get('equipment_code')))
    equip.manufacturer_code = Code.objects.get(id=int(request.POST.get('manufacturer_code')))
    equip.state_code = Code.objects.get(id=int(request.POST.get('state_code')))
    equip.model_no = request.POST.get('model_no', '')
    equip.serial_no = request.POST.get('serial_no', '')
    equip.purchase_ymd = request.POST.get('purchase_ymd', '').replace('-', '')
    equip.purchase_price = request.POST.get('purchase_price', '')
    equip.discard_ymd = request.POST.get('discard_ymd', '').replace('-', '')
    equip.detail_info = request.POST.get('detail_info', '')
    equip.save()

    return HttpResponseRedirect(reverse('equipment:equip_view', args=(equip.id,)))


def equip_view(request, sid):
    equipment = get_object_or_404(Equipment, pk=sid)
    return render(request, 'equipment/equip_view.html', {'equipment': equipment})


def equip_updform(request, sid):
    type_list = Code.objects.filter(code_category_id=1).all()
    manufacturer_list = Code.objects.filter(code_category_id=2).all()
    state_list = Code.objects.filter(code_category_id=3).all()
    equipment = get_object_or_404(Equipment, pk=sid)

    context = {'type_list': type_list, 'manufacturer_list': manufacturer_list, 'state_list': state_list, 'equipment': equipment}

    return render(request, 'equipment/equip_updform.html', context)


# @csrf_exempt
def equip_upd(request):
    if request.method != 'POST':
        resp = {
            'status': 'bad request'
        }
        return to_json(resp, 400)

    sid = request.POST.get('equipment_id')

    if sid != '0':
        equip = Equipment.objects.get(id=sid)
    else:
        resp = {
            'status': 'bad request'
        }
        return to_json(resp, 400)

    try:
        equip.equipment_code = Code.objects.get(id=int(request.POST.get('equipment_code')))
        equip.manufacturer_code = Code.objects.get(id=int(request.POST.get('manufacturer_code')))
        equip.state_code = Code.objects.get(id=int(request.POST.get('state_code')))
        equip.model_no = request.POST.get('model_no', '')
        equip.serial_no = request.POST.get('serial_no', '')
        equip.purchase_ymd = request.POST.get('purchase_ymd', '').replace('-', '')
        equip.purchase_price = request.POST.get('purchase_price', '')
        equip.discard_ymd = request.POST.get('discard_ymd', '').replace('-', '')
        equip.detail_info = request.POST.get('detail_info', '')
        equip.save()

        return HttpResponseRedirect(reverse('equipment:equip_view', args=(sid,)))
    except:
        resp = {
            'status': 'bad request'
        }
        return to_json(resp, 400)


def to_json(objs, status=200):
    json_str = json.dumps(objs, ensure_ascii=False)
    return HttpResponse(json_str, status=status, content_type='application/json; charset=utf-8')


def serialize(objs):
    return map(lambda x: x.serialize(), objs)


def equip_history_view(request, sid):
    project_list = Project.objects.all().order_by('start_ymd')
    serial = []

    if project_list:
        for p in project_list:
            serial.append(p.serialize())

    if sid != '0':
        history = get_object_or_404(History, pk=sid)
        return to_json({'history': history.serialize(), 'project_list': serial})
    else:
        return to_json({'history': {}, 'project_list': serial})


# @csrf_exempt
def equip_history_upd(request, sid):
    if request.method != 'POST':
        resp = {
            'status': 'bad request'
        }
        return to_json(resp, 400)

    if sid != '0':
        history = History.objects.get(id=sid)
    else:
        history = History()

    try:
        history.equipment = Equipment.objects.get(id=int(request.POST.get('equipment_id')))
        history.user_name = request.POST.get('user_name', '')
        history.start_ymd = request.POST.get('start_ymd', '').replace('-', '')
        history.end_ymd = request.POST.get('end_ymd', '').replace('-', '')
        history.project = Project.objects.get(id=int(request.POST.get('project_id')))
        history.save()
        return to_json({'status': 'create success'})
    except:
        resp = {
            'status': 'bad request'
        }
        return to_json(resp, 400)


def code_updform(request, sid):
    code_category_list = CodeCategory.objects.all().order_by('category_name')
    serial = []

    if code_category_list:
        for p in code_category_list:
            serial.append(p.serialize())

    if sid != '0':
        code = get_object_or_404(Code, pk=sid)
        return to_json({'code': code.serialize(), 'code_category_list': serial})
    else:
        return to_json({'code': {}, 'code_category_list': serial})


# @csrf_exempt
def code_upd(request):

    if request.method != 'POST':
        resp = {
            'status': 'bad request'
        }
        return to_json(resp, 400)

    sid = request.POST.get('modal_code_id')

    if sid != '0':
        code = Code.objects.get(id=sid)
    else:
        resp = {
            'status': 'bad request'
        }
        return to_json(resp, 400)

    try:
        code.code_category = CodeCategory.objects.get(id=int(request.POST.get('modal_code_category_id')))
        code.code_name = request.POST.get('modal_code_name')
        code.save()
        return to_json({'status': 'create success'})
    except:
        resp = {
            'status': 'bad request'
        }
        return to_json(resp, 400)


# @csrf_exempt
def code_add(request):
    code = Code()

templates/equipment/code_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="content">

    <div class="row">
        <div class="page-header">
            <h2><a href="/">Home</a>&nbsp;&nbsp;>&nbsp;&nbsp;코드 관리</h2>
        </div>
    </div>
    <div class="row">
        <form action="{% url 'equipment:code_list' %}" method="get" id="list_form">
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td class="active">코드 분류</td>
                    <td>
                        <select id="code_category_id" name="code_category_id" class="selectpicker show-tick form-control" data-live-search="true" title="코드 분류 선택" data-live-search-placeholder="Search...">
                            <option value="" {% if request.GET.code_category_id %}{% else %}selected{% endif %}>전체</option>
                            {% if code_category_list %}
                                {% for code_category in code_category_list %}
                                    <option value="{{ code_category.id }}" {% if request.GET.code_category_id|stringformat:"s" == code_category.id|stringformat:"s" %}selected{% endif %}>{{ code_category.category_name }}</option>
                                {% endfor %}
                            {% endif %}
                        </select>
                    </td>
                    <td class="active">코드명</td>
                    <td>
                        <input type="text" class="form-control" id="code_name" name="code_name" value="{{ request.GET.code_name }}" placeholder="코드명" maxlength="20">
                    </td>
                </tr>
                </tbody>
            </table>
        </form>
    </div>

    <div align="right">
        <button type="button" class="btn btn-primary" id="code_addform">코드 등록</button>
        <button type="button" class="btn btn-primary" id="code_list">검색</button>
    </div>

    <div class="row">
        <br/>
        <div align="center">총 {{ total_count }} 건이 검색되었습니다.</div>
        <br/>
        <table class="table table-hover">
            <thead>
                <th width="30%">코드 분류</th>
                <th width="30%">코드명</th>
                <th width="40%">수정</th>
            </thead>
            <tbody>
            </tbody>
        </table>
        {% include page_template %}
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <form action="" method="post" id="register_form">
{#                    {% csrf_token %}#}
                    <div class="modal-body">
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <td class="active">코드 분류</td>
                                <td>
                                    <input type="hidden" class="form-control" id="modal_code_id" name="modal_code_id" value="">
                                    <span id="code_category_list"/></td>
                                <td class="active">코드명</td>
                                <td><input type="text" class="form-control" id="modal_code_name" name="modal_code_name" value="" maxlength="100"></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="code_upd">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

<script src="{% static 'equipment/equipment.js' %}"></script>
<script src="{% static 'equipment/ext/el-pagination.js' %}"></script>
<script>
    $.endlessPaginate({
        paginateOnScroll: true,
        paginateOnScrollMargin: 10,
    });
</script>
<script>
    $(document).ready(function() {
        $(document).on("click", "#code_addform", code_addform);
        $(document).on("click", "#code_list", code_list);
        $(document).on("click", "#code_updform", code_updform);
        $(document).on("click", "#code_upd", code_upd);
    });
    var code_addform = function () {
        location.href = "{% url 'equipment:code_addform' %}"
    };
    var code_list = function () {
        $("#list_form").submit();
    };
</script>

{% endblock %}

templates/equipment/code_list_page.html
{% load humanize %}
{% load el_pagination_tags %}
{% paginate list %}

<table class="table table-hover">
    <tbody>
{% for obj in list %}
    <tr>
        <td width="30%">{{ obj.code_category.category_name }}</td>
        <td width="30%">{{ obj.code_name }}</td>
        <td width="40%">
            <div>
                <button type="button" class="btn btn-default btn-xs" id="code_updform" aria-label="Left Align" value="{{ obj.id }}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </button>
            </div>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% show_more "더 보기" "불러오고 있습니다." %}

templates/equipment/equip_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="content">

    <div class="row">
        <div class="page-header">
            <h2><a href="/">Home</a>&nbsp;&nbsp;>&nbsp;&nbsp;자산 목록</h2>
        </div>
    </div>
    <div class="row">
        <form action="{% url 'equipment:equip_list' %}" method="get" id="list_form">
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td class="active">자산분류</td>
                    <td>
                        <select id="equipment_code" name="equipment_code" class="selectpicker show-tick form-control" data-live-search="true" title="자산 분류 선택" data-live-search-placeholder="Search...">
                            <option value="" {% if request.GET.equipment_code %}{% else %}selected{% endif %}>전체</option>
                            {% if type_list %}
                                {% for type in type_list %}
                                    <option value="{{ type.id }}" {% if request.GET.equipment_code|stringformat:"s" == type.id|stringformat:"s" %}selected{% endif %}>{{ type.code_name }}</option>
                                {% endfor %}
                            {% endif %}
                        </select>
                    </td>
                    <td class="active">자산 상태</td>
                    <td>
                        <select id="state_code" name="state_code" class="selectpicker show-tick form-control" data-live-search="true" title="자산 상태 선택" data-live-search-placeholder="Search...">
                            <option value="" {% if request.GET.state_code %}{% else %}selected{% endif %}>전체</option>
                            {% if state_list %}
                                {% for state in state_list %}
                                    <option value="{{ state.id }}" {% if request.GET.state_code|stringformat:"s" == state.id|stringformat:"s" %}selected{% endif %}>{{ state.code_name }}</option>
                                {% endfor %}
                            {% endif %}
                        </select>
                    </td>
                    <td class="active">프로젝트</td>
                    <td>
                        <select id="project_code" name="project_code" class="selectpicker show-tick form-control" data-live-search="true" title="프로젝트 선택" data-live-search-placeholder="Search...">
                            <option value="" {% if request.GET.project_code %}{% else %}selected{% endif %}>전체</option>
                            {% if project_list %}
                                {% for project in project_list %}
                                    <option value="{{ project.id }}" {% if request.GET.project_code|stringformat:"s" == project.id|stringformat:"s" %}selected{% endif %}>{{ project.project_name }}</option>
                                {% endfor %}
                            {% endif %}
                        </select>
                    </td>
                    <td class="active">사용자</td>
                    <td>
                        <input type="text" class="form-control" id="user_name" name="user_name" value="{{ request.GET.user_name }}" placeholder="사용자 이름" maxlength="20">
                    </td>
                </tr>
                </tbody>
            </table>
        </form>
    </div>

    <div class="row">
        <div class="col-md-4" align="left">
            <button type="button" class="btn btn-primary" id="equip_csv">CSV 내려받기</button>
        </div>
        <div class="col-md-8" align="right">
            <button type="button" class="btn btn-primary" id="equip_addform">자산 등록</button>
            <button type="button" class="btn btn-primary" id="equip_list">검색</button>
        </div>
    </div>

    <div class="row">
        <br/>
        <div align="center">총 {{ total_count }} 건이 검색되었습니다.</div>
        <br/>
        <table class="table table-hover">
            <thead>
                <th width="9%">자산분류</th>
                <th width="22%">자산명</th>
                <th width="22%">시리얼번호</th>
                <th width="10%">취득일</th>
                <th width="10%">취득가격</th>
                <th width="8%">사용여부</th>
                <th width="10%">등록일</th>
                <th width="7%">사용자</th>
            </thead>
            <tbody>
            </tbody>
        </table>
        {% include page_template %}
    </div>

</div>

    <script src="{% static 'equipment/equipment.js' %}"></script>
    <script src="{% static 'equipment/ext/el-pagination.js' %}"></script>
    <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollMargin: 10,
        });
    </script>
    <script>
        $(document).ready(function() {
            $(document).on("click", "#equip_addform", equip_addform);
            $(document).on("click", "#equip_list", equip_list);
            $(document).on("click", "#equip_csv", equip_csv);
        });
        var equip_addform = function () {
            location.href = "{% url 'equipment:equip_addform' %}"
        };
        var equip_list = function () {
            $("#list_form").attr('action', '{% url "equipment:equip_list" %}');
            $("#list_form").submit();
        };
        var equip_csv = function () {
            $("#list_form").attr('action', '{% url "equipment:equip_csv" %}');
            $("#list_form").submit();
        };
    </script>

{% endblock %}

templates/equipment/pjt_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="content">

    <div class="row">
        <div class="page-header">
            <h2><a href="/">Home</a>&nbsp;&nbsp;>&nbsp;&nbsp;프로젝트 관리</h2>
        </div>
    </div>
    <div class="row">
        <form action="{% url 'equipment:pjt_list' %}" method="get" id="list_form">
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td class="active">프로젝트명</td>
                    <td>
                        <input type="text" class="form-control" id="project_name" name="project_name" value="{{ request.GET.project_name }}" placeholder="프로젝트명" maxlength="20">
                    </td>
                </tr>
                </tbody>
            </table>
        </form>
    </div>

    <div align="right">
        <button type="button" class="btn btn-primary" id="project_addform">프로젝트 등록</button>
        <button type="button" class="btn btn-primary" id="project_list">검색</button>
    </div>

    <div class="row">
        <br/>
        <div align="center">총 {{ total_count }} 건이 검색되었습니다.</div>
        <br/>
        <table class="table table-hover">
            <thead>
                <th width="25%">프로젝트명</th>
                <th width="25%">시작일</th>
                <th width="25%">종료일</th>
                <th width="25%">수정</th>
            </thead>
            <tbody>
            </tbody>
        </table>
        {% include page_template %}
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <form action="" method="post" id="register_form">
                    {#                    {% csrf_token %}#}
                    <div class="modal-body">
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <td class="active">프로젝트명</td>
                                <td colspan="3">
                                    <input type="hidden" class="form-control" id="modal_project_id" name="modal_project_id" value="">
                                    <input type="text" class="form-control" id="modal_project_name" name="modal_project_name" value="" placeholder="프로젝트명" maxlength="30">
                                </td>
                            </tr>
                            <tr>
                                <td class="active">시작일</td>
                                <td><input type="text" class="form-control" id="modal_start_ymd" name="modal_start_ymd" value="" placeholder="yyyy-MM-dd" maxlength="10"></td>
                                <td class="active">종료일</td>
                                <td><input type="text" class="form-control" id="modal_end_ymd" name="modal_end_ymd" value="" placeholder="yyyy-MM-dd" maxlength="10"></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="project_upd">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>

<script src="{% static 'equipment/equipment.js' %}"></script>
<script src="{% static 'equipment/ext/el-pagination.js' %}"></script>
<script>
    $.endlessPaginate({
        paginateOnScroll: true,
        paginateOnScrollMargin: 10,
    });
</script>
<script>
    $(document).ready(function() {
        $(document).on("click", "#project_addform", project_addform);
        $(document).on("click", "#project_list", project_list);
        $(document).on("click", "#project_updform", project_updform);
        $(document).on("click", "#project_upd", project_upd);
    });
    var project_addform = function () {
        location.href = "{% url 'equipment:pjt_addform' %}"
    };
    var project_list = function () {
        $("#list_form").submit();
    };
</script>

{% endblock %}

templates/equipment/pjt_list_page.html
{% load humanize %}
{% load el_pagination_tags %}
{% paginate list %}

<table class="table table-hover">
    <tbody>
{% for obj in list %}
    <tr>
        <td width="25%">{{ obj.project_name }}</td>
        <td width="25%">{{ obj.start_ymd|slice:'0:4' }}-{{ obj.start_ymd|slice:'4:6' }}-{{ obj.start_ymd|slice:'6:8' }}</td>
        <td width="25%">{{ obj.end_ymd|slice:'0:4' }}-{{ obj.end_ymd|slice:'4:6' }}-{{ obj.end_ymd|slice:'6:8' }}</td>
        <td width="25%">
            <div>
                <button type="button" class="btn btn-default btn-xs" id="project_updform" aria-label="Left Align" value="{{ obj.id }}">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </button>
            </div>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% show_more "더 보기" "불러오고 있습니다." %}